#!/usr/bin/env bash
# Conf your domain so that the subdomain points to your load-balancer.

func_domain_conf () {
    d="$1"
    sbd="$2"
    if [ ! -z "$d" ] && [ ! -z "$sbd" ]; then
	dig "$sbd.$d" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk -v mysb="$sbd" '{print "The subdomain " mysb " is a "  $4 " record and points to "$5}'
    elif [ ! -z "$d" ]; then
	dig "www.$d" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{print "The subdomain www is a " $4 " record and points to "$5}'
	dig "lb-01.$d" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{print "The subdomain lb-01 is a " $4 " record and points to "$5}'
	dig "web-01.$d" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{print "The subdomain web-01 is a " $4 " record and points to "$5}'
	dig "web-02.$d" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{print "The subdomain web-02 is a " $4 " record and points to "$5}'
    fi
}

func_domain_conf "$1" "$2"
