#!/usr/bin/env bash
#Installs nginx

apt-get update
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.html
sudo sed -i "35i add_header X-Served-By \$hostname always;" /etc/nginx/sites-available/default
service nginx restart
