#!/usr/bin/env bash
#Installs nginx

apt-get -y update
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /etc/nginx/html;
        internal;
        }
}" > /etc/nginx/sites-available/default
sudo sed -i "35i add_header X-Served-By \$hostname always;" /etc/nginx/sites-available/default
service nginx restart
