#!/usr/bin/env bash
#Installs nginx

apt-get update
apt-get install -y nginx
echo "Holberton School" > /etc/www/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default
sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /var/www/html;\ninternal;\n}' /etc/nginx/sites-available/default
sed -i '/server_name _;/ a add_header X-Served-By "\$HOSTNAME";' /etc/nginx/sites-available/default
service nginx restart
