#!/usr/bin/env bash
# Installs nginx

apt-get update
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.html

sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /var/www/html;\ninternal;\n}' /etc/nginx/sites-available/default
sed -i '/server_name _;/ a add_header X-Served-By "\$HOSTNAME";' /etc/nginx/sites-available/default
service nginx start
