#!/usr/bin/env bash
# runs nginx using nginx user
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
